### ISSUE TITLE
TL-WR844N supported ?

### ISSUE THREAD

**Issue by barbuslex** [AlexandrErohin/TP-Link-Archer-C6U#59]
Hi,

TL-WR844N is it supported ? i have not see this reference in documentation.

Thanks

**Comment by AlexandrErohin** [comment]
Hi, There wasnt info about TL-WR844N. If you have it - would be great if you could test

**Comment by barbuslex** [comment]
I will receive 2x TL-WR844N models next week... I will try...
Is there a special configuration to do for unsupported models?

**Comment by AlexandrErohin** [comment]
No special configuration

**Comment by barbuslex** [comment]
Ok I'll test next week and I'll give you feedback

**Comment by barbuslex** [comment]
I have try to add it today, i have this error : 
![image](https://github.com/user-attachments/assets/7401b256-665c-411e-88ea-504ada841bd0)

**Comment by AlexandrErohin** [comment]
So it is not supported. Would be great if you could add support for your router. Here are the examples how to do it https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/CONTRIBUTING.md

**Comment by barbuslex** [comment]
Yes of course i Can try...

What IS the serie of TL-WR844N model ? TL series ?

**Comment by AlexandrErohin** [comment]
@barbuslex You may implement methods for this class https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/tplinkrouterc6u/client/c6v4.py, It looks like API the same for these routers

**Comment by AlexandrErohin** [comment]
@barbuslex Hi! Could you try the HA integration latest version please?

**Comment by barbuslex** [comment]
I have tried : 

![Image](https://github.com/user-attachments/assets/5a4f6029-3074-4871-a9c9-ad998d547caa)

It seems in TL-WR844N there are not have username : 

![Image](https://github.com/user-attachments/assets/3440ee2c-3348-4646-bd2a-6b7ea1dc805d)

**Comment by dennismdejong** [comment]
> *This was generated by AI during triage.*

## Status update: support has been added

Support for the TL-WR844N has since been added in `main` via PR #179: the router is picked up by the **c80 client** (the status response identifies `modelName TL-WR844N`, and parsing is covered by a test, including the no-wifi status shape).

**On the "no username" point:** this is not a blocker — the c80 client uses password-only encryption (`_encrypt_password`); the default `admin` username is not part of the login exchange.

@barbuslex — could you please test the latest version (5.32.1+) again?

```python
from tplinkrouterc6u import TplinkRouterProvider
router = TplinkRouterProvider.get_client("http://192.168.0.1", "your_password")
print(router.__class__)
router.authorize()
firmware = router.get_firmware()
print(firmware)
```

If it works, we can close this issue. If it still fails, please share the exact error message.

Note: there is also an alternative dedicated `wr844n.py` client in the `beta` branch (PR #167) — if the c80 route has issues on your firmware, we can compare.

**Comment by dennismdejong** [comment]
> *This was generated by AI during triage.*

## Follow-up: the exact failure is now identified

Reviewing the screenshot you posted (2025-03), the error was:

```
binascii.Error: Invalid base64-encoded string: number of data characters (5) cannot be 1 more than a multiple of 4
  File ".../tplinkrouterc6u/client/c80.py", in _decrypt_data
    decrypted_padded = cipher.decrypt(b64decode(encrypted_text))
```

**Root cause:** the c80 client only recognises plain-text replies starting with `00000\r\n`. A reply that starts with the OK marker but has no CRLF (e.g. a bare `00000`) was fed to `b64decode()`, which raises because 5 characters is not a multiple of 4.

I have opened PR #223 which makes `_decrypt_data()` return a `00000`-prefixed, non-base64 reply as plain text instead of crashing.

@barbuslex — with the latest version + PR #223, could you test again and share the result (and, if it still fails, the full traceback)?

**Comment by barbuslex** [comment]
On 5.32.1 i have this error : 
```powershell
PS D:\Temp\TP-Link-Archer-C6U-5.32.1> python test.py
Traceback (most recent call last):
  File "D:\Temp\TP-Link-Archer-C6U-5.32.1\test.py", line 1, in <module>
    from tplinkrouterc6u import TplinkRouterProvider
  File "D:\Temp\TP-Link-Archer-C6U-5.32.1\tplinkrouterc6u\__init__.py", line 1, in <module>
    from tplinkrouterc6u.client.c6u import TplinkRouter, TplinkRouterV1_11
  File "D:\Temp\TP-Link-Archer-C6U-5.32.1\tplinkrouterc6u\client\c6u.py", line 5, in <module>
    from requests import post, Response
ModuleNotFoundError: No module named 'requests'
PS D:\Temp\TP-Link-Archer-C6U-5.32.1> py test.py
<class 'tplinkrouterc6u.client.re330.TplinkRE330Router'>
Traceback (most recent call last):
  File "D:\Temp\TP-Link-Archer-C6U-5.32.1\test.py", line 5, in <module>
    firmware = router.get_firmware()
  File "D:\Temp\TP-Link-Archer-C6U-5.32.1\tplinkrouterc6u\client\re330.py", line 122, in get_firmware
    response_text = self._decrypt_data(response.text)
  File "D:\Temp\TP-Link-Archer-C6U-5.32.1\tplinkrouterc6u\client\re330.py", line 374, in _decrypt_data
    return self._encryption.aes.aes_decrypt(encrypted_text)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "D:\Temp\TP-Link-Archer-C6U-5.32.1\tplinkrouterc6u\common\encryption.py", line 28, in aes_decrypt
    enc = b64decode(enc)
  File "C:\Users\Barbuslex\AppData\Local\Programs\Python\Python314\Lib\base64.py", line 85, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Invalid base64-encoded string: number of data characters (5) cannot be 1 more than a multiple of 4
```
On beta branch i have this one : 
```powershell
PS D:\Temp\TP-Link-Archer-C6U-beta> py test.py
<class 'tplinkrouterc6u.client.re330.TplinkRE330Router'>
Traceback (most recent call last):
  File "D:\Temp\TP-Link-Archer-C6U-beta\test.py", line 5, in <module>
    firmware = router.get_firmware()
  File "D:\Temp\TP-Link-Archer-C6U-beta\tplinkrouterc6u\client\re330.py", line 122, in get_firmware
    response_text = self._decrypt_data(response.text)
  File "D:\Temp\TP-Link-Archer-C6U-beta\tplinkrouterc6u\client\re330.py", line 374, in _decrypt_data
    return self._encryption.aes.aes_decrypt(encrypted_text)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "D:\Temp\TP-Link-Archer-C6U-beta\tplinkrouterc6u\common\encryption.py", line 28, in aes_decrypt
    enc = b64decode(enc)
  File "C:\Users\Barbuslex\AppData\Local\Programs\Python\Python314\Lib\base64.py", line 85, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Invalid base64-encoded string: number of data characters (5) cannot be 1 more than a multiple of 4
```

**Comment by dennismdejong** [comment]
> *This was generated by AI during triage.*

Thank you for the detailed test output. Two important findings:

1. The provider now selects the **re330 client** for the WR844N (not c80), and re330 has the same decryption assumption — so the c80 fix does not help here.
2. The error shows `number of data characters (5)`, which strongly suggests the router answers with a bare `00000` (the OK marker only, no CRLF and no payload).

To make the fix correct we need to see the **actual raw response** the router returns for `get_firmware()`. Could you run this and share the printed output?

```python
from tplinkrouterc6u.client.re330 import TplinkRE330Router

class DebugRouter(TplinkRE330Router):
    def _decrypt_data(self, encrypted_text: str) -> str:
        print("RAW repr:", repr(encrypted_text))
        print("RAW hex :", encrypted_text.encode("utf-8", errors="replace").hex())
        return super()._decrypt_data(encrypted_text)

router = DebugRouter("http://192.168.0.1", "your_password")
router.authorize()
router.get_firmware()
```

The `repr` shows the exact characters (including any `\r\n`), and the hex confirms the byte content. With that we can fix the right client class (and distinguish `00000` from `00000\r\n...`).

**Comment by barbuslex** [comment]
Here the result @dennismdejong : 
```powershell
PS D:\Temp\TP-Link-Archer-C6U-beta> py test.py
RAW repr: '00006\r\n'
RAW hex : 30303030360d0a
Traceback (most recent call last):
  File "D:\Temp\TP-Link-Archer-C6U-beta\test.py", line 11, in <module>
    router.get_firmware()
    ~~~~~~~~~~~~~~~~~~~^^
  File "D:\Temp\TP-Link-Archer-C6U-beta\tplinkrouterc6u\client\re330.py", line 123, in get_firmware
    response_text = self._decrypt_data(response.text)
  File "D:\Temp\TP-Link-Archer-C6U-beta\test.py", line 7, in _decrypt_data
    return super()._decrypt_data(encrypted_text)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "D:\Temp\TP-Link-Archer-C6U-beta\tplinkrouterc6u\client\re330.py", line 387, in _decrypt_data
    return self._encryption.aes.aes_decrypt(encrypted_text)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "D:\Temp\TP-Link-Archer-C6U-beta\tplinkrouterc6u\common\encryption.py", line 28, in aes_decrypt
    enc = b64decode(enc)
  File "C:\Users\Barbuslex\AppData\Local\Programs\Python\Python314\Lib\base64.py", line 85, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Invalid base64-encoded string: number of data characters (5) cannot be 1 more than a multiple of 4
```

**Comment by dennismdejong** [comment]
> *This was generated by AI during triage.*

Thank you — that confirms it. The raw response for `get_firmware()` is **`00006\r\n`** (hex `30303030360d0a`): the `0000` OK/error marker followed by error code `6`, not an encrypted payload. The client was crashing trying to base64-decode it.

I have opened/updated **PR #223** which fixes this for both the re330 and c80 clients:
- Any `0000`-prefixed reply that is not valid base64 (e.g. `00006\r\n`, a bare `00000`) is now returned as plain text instead of being fed to `b64decode`.
- Encrypted payloads are decrypted unchanged.

Note: this stops the crash, but `get_firmware()` on the WR844N will still not return firmware data via this request (the router answers with error code `6`, i.e. it does not support that request). We need the maintainer to advise whether a different request/endpoint is needed for the WR844N firmware, or whether get_firmware support is simply not available on this model.

**Comment by barbuslex** [comment]
The return of PR #223 on main : 
```powershell
PS D:\Temp\TP-Link-Archer-C6U> py test.py
RAW repr: '00006\r\n'
RAW hex : 30303030360d0a
Traceback (most recent call last):
  File "D:\Temp\TP-Link-Archer-C6U\test.py", line 11, in <module>
    router.get_firmware()
    ~~~~~~~~~~~~~~~~~~~^^
  File "D:\Temp\TP-Link-Archer-C6U\tplinkrouterc6u\client\re330.py", line 125, in get_firmware
    return Firmware(parse.unquote(device_datamap['hardVer']), parse.unquote(device_datamap['modelName']),
                                  ~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'hardVer'
```

**Comment by dennismdejong** [comment]
> *This was generated by AI during triage.*

Thanks again for testing. The emulator data you shared confirms the request `code=2&asyn=1` with `0|1,0,0` IS valid for the WR844N and returns the full firmware block. So the failure on your real router is specifically the **encrypted** request being rejected (error code 6).

To pinpoint it, could you run this script (from your `TP-Link-Archer-C6U` folder) and paste the full output?

```python
import sys
sys.path.insert(0, ".")
from tplinkrouterc6u.client.re330 import TplinkRE330Router

class DebugRouter(TplinkRE330Router):
    def request(self, code, asyn, use_token=False, data=None):
        response = super().request(code, asyn, use_token, data)
        print("--- request code={} asyn={} use_token={}".format(code, asyn, use_token))
        print("    sent:  " + repr(data)[:150])
        print("    got:   " + repr(response.text)[:300])
        return response

router = DebugRouter("http://192.168.0.1", "your_admin_password")
router.authorize()
print("=== authorize done ===")

try:
    fw = router.get_firmware()
    print("get_firmware OK:", fw)
except Exception as e:
    print("get_firmware FAIL:", e)

print("\n--- experiment: plain '0|1,0,0' WITH token (asyn=1) ---")
try:
    r = router.request(2, 1, True, data="0|1,0,0")
    print("raw:", repr(r.text))
except Exception as e:
    print("FAIL:", e)

print("\n--- experiment: plain '0|1,0,0' WITHOUT token (asyn=0) ---")
try:
    r = router.request(2, 0, data="0|1,0,0")
    print("raw:", repr(r.text))
except Exception as e:
    print("FAIL:", e)
```

**What this tells us:**
1. Whether every `authorize()` step returns `00000` (or if one returns `00006` — that would point to the session/key setup).
2. Whether the WR844N accepts the firmware request **plain** (experiments 1 and 2) instead of encrypted.
3. The exact bytes it returns for each variant.

**Additionally:** if you can export a HAR of the real router web UI (browser devtools > Network, log in, then load the dashboard and save HAR), that shows exactly how the working web UI performs the same `code=2&asyn=1` call (encrypted body? `id` param present?).

**Comment by barbuslex** [comment]
```powershell
PS D:\Temp\TP-Link-Archer-C6U> py test.py
--- request code=7 asyn=1 use_token=False
    sent:  None
    got:   '00007\r\n00004\r\n00000\r\nbK|A{dXWG|M4$AE70Z]$,{ytCE.uz5Cs\r\ncPE7B|iThE+jKOx>}AB(TB$6)!lmh6Y]EO)b,PXnb,0O},}0vTvOPPc4xj25MhWcLrX!6e>yWng}CgnZ1*Xwe>7LDGDt7Asy++vc9nc!UAmI0w496!+e7j610QOtt}tC>.N(1b>Fk0Usa.E(v$$qVSLV*kHEU0P{I3eG1U|s^meXOoXS,{h+K$tBG!<k.RGR6${{w$[xjrm4xq+>eXG4xA,VlS1ABccA)6ihjiFGtn.(
--- request code=16 asyn=0 use_token=False
    sent:  'get'
    got:   '00000\r\n010001\r\nBF9AE9F6B44C830C91BE2063CE659F4F24230F732FEA9E413474A6623658D26B91603A46273E3ED567FE1A513B93C3BB449D7BA4971A3DBB44760988B9792EFB\r\n890509898\r\n\r\n'
--- request code=7 asyn=0 use_token=True
    sent:  None
    got:   '00000\r\n'
--- request code=16 asyn=0 use_token=True
    sent:  'set 94782c13aa4ef652ce0e7f1deace0188284fc0c45587a867d8dfb02fe67f107b666d4d275467da62b7145062eccb6a5f5438637b321336673ebdf69549a15b44'
    got:   '00000\r\n'
=== authorize done ===
--- request code=2 asyn=1 use_token=True
    sent:  'sign=15d0a4eedb0a92413e862209ebd814d65a8702c2034ac893ad02424dea52e70ee74ae83ba4c7f7fccb8c8cbff0ccac95610697fba06197a2f1f65bf144d72b26\r\ndata=cM9O9yW
    got:   '00006\r\n'
get_firmware FAIL: 'hardVer'

--- experiment: plain '0|1,0,0' WITH token (asyn=1) ---
--- request code=2 asyn=1 use_token=True
    sent:  '0|1,0,0'
    got:   '00000\r\nid 0|1,0,0\r\nfullName 300Mbps%20Wi-Fi%20Router\r\nfacturer TP-Link\r\nmodelName TL-WR844N\r\nmodelVer 1.0\r\nsoftVer 1.15.20%20Build%20260611%20Rel.30987n(4555)\r\nhardVer TL-WR844N%201.0\r\nspecialId 0x5545\r\ncountryCode 0x4544\r\nmainVer 0x5a010f14\r\nminorVer 0x1\r\noem_id D1F6BD89042
raw: '00000\r\nid 0|1,0,0\r\nfullName 300Mbps%20Wi-Fi%20Router\r\nfacturer TP-Link\r\nmodelName TL-WR844N\r\nmodelVer 1.0\r\nsoftVer 1.15.20%20Build%20260611%20Rel.30987n(4555)\r\nhardVer TL-WR844N%201.0\r\nspecialId 0x5545\r\ncountryCode 0x4544\r\nmainVer 0x5a010f14\r\nminorVer 0x1\r\noem_id D1F6BD890424AFCDBB913A3F281FC871\r\nfacturerType 0\r\nanatelSupport 0\r\n'

--- experiment: plain '0|1,0,0' WITHOUT token (asyn=0) ---
--- request code=2 asyn=0 use_token=False
    sent:  '0|1,0,0'
    got:   '00000\r\nid 0|1,0,0\r\nfullName 300Mbps%20Wi-Fi%20Router\r\nfacturer TP-Link\r\nmodelName TL-WR844N\r\nmodelVer 1.0\r\nsoftVer 1.15.20%20Build%20260611%20Rel.30987n(4555)\r\nhardVer TL-WR844N%201.0\r\nspecialId 0x5545\r\ncountryCode 0x4544\r\nmainVer 0x5a010f14\r\nminorVer 0x1\r\noem_id D1F6BD89042
raw: '00000\r\nid 0|1,0,0\r\nfullName 300Mbps%20Wi-Fi%20Router\r\nfacturer TP-Link\r\nmodelName TL-WR844N\r\nmodelVer 1.0\r\nsoftVer 1.15.20%20Build%20260611%20Rel.30987n(4555)\r\nhardVer TL-WR844N%201.0\r\nspecialId 0x5545\r\ncountryCode 0x4544\r\nmainVer 0x5a010f14\r\nminorVer 0x1\r\noem_id D1F6BD890424AFCDBB913A3F281FC871\r\nfacturerType 0\r\nanatelSupport 0\r\n'
```

Here the HAR file (is it safe to share it here ?) : 
[Archive \[26-09-09 10-58-28\].zip](https://github.com/user-attachments/files/31999468/Archive.26-09-09.10-58-28.zip)

code=2
asyn=0

**Comment by AlexandrErohin** [comment]
@barbuslex Please try the latest version of the integration

**Comment by barbuslex** [comment]
@AlexandrErohin The result (with last test script): 
```powershell
PS D:\Temp\TP-Link-Archer-C6U-5.34.0> py .\test.py
RAW repr: '00000\r\nid 0|1,0,0\r\nfullName 300Mbps%20Wi-Fi%20Router\r\nfacturer TP-Link\r\nmodelName TL-WR844N\r\nmodelVer 1.0\r\nsoftVer 1.15.20%20Build%20260611%20Rel.30987n(4555)\r\nhardVer TL-WR844N%201.0\r\nspecialId 0x5545\r\ncountryCode 0x4544\r\nmainVer 0x5a010f14\r\nminorVer 0x1\r\noem_id D1F6BD890424AFCDBB913A3F281FC871\r\nfacturerType 0\r\nanatelSupport 0\r\n'
RAW hex : 30303030300d0a696420307c312c302c300d0a66756c6c4e616d65203330304d62707325323057692d4669253230526f757465720d0a66616374757265722054502d4c696e6b0d0a6d6f64656c4e616d6520544c2d57523834344e0d0a6d6f64656c56657220312e300d0a736f667456657220312e31352e32302532304275696c6425323032363036313125323052656c2e33303938376e2834353535290d0a6861726456657220544c2d57523834344e253230312e300d0a7370656369616c4964203078353534350d0a636f756e747279436f6465203078343534340d0a6d61696e56657220307835613031306631340d0a6d696e6f72566572203078310d0a6f656d5f69642044314636424438393034323441464344424239313341334632383146433837310d0a66616374757265725479706520300d0a616e6174656c537570706f727420300d0a
```

**Comment by AlexandrErohin** [comment]
@barbuslex Have you tried the latest version of Home Assistant component?

**Comment by barbuslex** [comment]
@AlexandrErohin it's works. Some sensor are unavailable : 

<img width="393" height="639" alt="Image" src="https://github.com/user-attachments/assets/824244c4-e80e-4317-958f-a7f3d1cccd85" />

**Comment by AlexandrErohin** [comment]
@barbuslex Great!
